### ISSUE TITLE
README connection example results in compiler error

### ISSUE THREAD

**Issue by mebmichael** [maxwellhealth/bongo#6]
The line
```go
connection := bongo.Connect(config)
```
does not assign the returned error variable to anything.
Maybe change it to
```go
connection, err := bongo.Connect(config)
if err != nil {
    panic(err)
}
```
and let the user decide if they want to just ignore the error with ```_```?

**Comment by mebmichael** [comment]
For reference, with the code from the README, the debugger gives the following error: `multiple-value bongo.Connect() in single-value context`

**Comment by jraede** [comment]
@mebmichael Good find! That was left over from a previous API in which `connect` did not return an error.
